apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  labels:
    app.kubernetes.io/name: navidrome
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: navidrome
  template:
    metadata:
      labels:
        app.kubernetes.io/name: navidrome
    spec:
      containers:
      - name: navidrome
        image: deluan/navidrome:latest
        ports:
        - containerPort: 4533
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "400Mi"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: music-volume
          mountPath: /music
      volumes:
      - name: data-volume
        emptyDir: {}
      - name: music-volume
        emptyDir: {}