apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
    {{- include "appLabels" . | nindent 4 }}
spec:
  {{ if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "commonLabels" . | nindent 4 }}
    app: navidrome