# Application settings
namespace: navidrome-system
image:
  repo: "deluan/navidrome"
  tag: "0.60.3"
  pullPolicy: IfNotPresent
containerPort: 4533
resources:
  limits:
    memory: 1536Mi
  requests:
    cpu: 1250m

# Service configuration
service:
  type: LoadBalancer
  port: 80

# Public endpoints configuration
baseDomain: "example.com"
clusterissuer:
  email: singhamitch@outlook.com
  name: letsencrypt-prod
certificate:
  secret: navidrome-cert

filebrowser:
  imageURI: "filebrowser/filebrowser:v2.61.0"
  reconfigImageUri: "ghcr.io/semmet95/navidrome-deployer/filebrowser-reconfig:0.20.1"
  containerPort: 80
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 500m
  service:
    port: 80